Die if one of the tarballs is damaged

diff --git a/bin/run-job b/bin/run-job
--- a/bin/run-job
+++ b/bin/run-job
@@ -134,7 +134,10 @@ if [ -f $INPUT_DIR/osg-test-git.tar.gz ]; then
     for PACKAGE in 'osg-test' 'osg-ca-generator'; do
         tarball=$INPUT_DIR/$PACKAGE-git.tar.gz
         log_command stat $tarball
-        tar xzf $tarball --directory /tmp
+        if ! log_command tar xzf $tarball --directory /tmp; then
+            echo "$tarball extraction failed"
+            exit 1
+        fi
         cd /tmp/$PACKAGE-git
         if [ "$os_major_version" -gt 7 ]; then
             find . -type f -exec sed -ri '1s,^#!/usr/bin/env python.*,#!'"$python"',' '{}' +
