Added support for an osg-test source tarball.
git-svn-id: https://vdt.cs.wisc.edu/svn/new-test/trunk/vm-test-runs@18525 4e558342-562e-0410-864c-e07659590f8c

diff --git a/run-job b/run-job
--- a/run-job
+++ b/run-job
@@ -106,18 +106,30 @@ if [ $? -ne 0 ]; then
 fi
 
 # Install osg-test
-RPM_LOCATION=`ls -1 $INPUT_DIR/osg-test-*.el$os_major_version.noarch.rpm 2>/dev/null | tail -n 1`
-if [ "x$RPM_LOCATION" != 'x' ]; then
-    log_command rpm --install $RPM_LOCATION
+if [ -f $INPUT_DIR/osg-test-trunk.tar.bz2 ]; then
+    tar xf $INPUT_DIR/osg-test-trunk.tar.bz2 --directory /tmp
+    cd /tmp/osg-test-trunk
+    make install DESTDIR=/
+    svn_revision=`cat svn-revision.txt`
+    log_command echo "osg-test source: svn trunk\@$svn_revision" # For post-run analysis
 else
-    run_command_with_retries 8 yum -y --enablerepo=osg-testing install osg-test
-    if [ $? -ne 0 ]; then
-        echo 'Could not install osg-test'
-        exit 1
+    RPM_LOCATION=`ls -1 $INPUT_DIR/osg-test-*.el$os_major_version.noarch.rpm 2>/dev/null | tail -n 1`
+    if [ "x$RPM_LOCATION" != 'x' ]; then
+        log_command rpm --install $RPM_LOCATION
+        log_command rpm --verify osg-test
+        rpm_version=`rpm --query osg-test`
+        log_command echo "osg-test source: file $rpm_version" # For post-run analysis
+    else
+        run_command_with_retries 8 yum -y --enablerepo=osg-testing install osg-test
+        if [ $? -ne 0 ]; then
+            echo 'Could not install osg-test'
+            exit 1
+        fi
+        log_command rpm --verify osg-test
+        rpm_version=`rpm --query osg-test`
+        log_command echo "osg-test source: yum $rpm_version" # For post-run analysis
     fi
 fi
-log_command rpm --verify osg-test
-log_command rpm --query osg-test # Primarily for analyze-test-run
 
 # Patch osg-test
 log_command yum -y install patch
